require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
  - 'docker/**/*'
  - 'node_modules/**/*'
  - 'db/schema.rb'
  - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/catalog_controller.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'


# Offense count: 12
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'app/models/search_builder.rb'
    - 'app/models/solr_document.rb'
    - 'config/application.rb'
    - 'db/migrate/*'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
