require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
  - 'docker/**/*'
  - 'node_modules/**/*'
  - 'db/schema.rb'
  - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/catalog_controller.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
