require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
  - 'node_modules/**/*'
  - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
