FROM ruby:2.6
LABEL maintainer="Justin Littman <justinlittman@stanford.edu>"

RUN mkdir /app-setup
WORKDIR /app-setup

RUN curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
RUN chmod +x nodesource_setup.sh
RUN ./nodesource_setup.sh
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
# netcat is required by wait-for in invoke.sh
RUN apt-get update && apt-get install -y build-essential postgresql-client tzdata git netcat nodejs yarn

ENV BUNDLER_VERSION 2.0.1

RUN gem install bundler

ENV RAILS_ENV development
ENV RAILS_SERVE_STATIC_FILES true

COPY Gemfile Gemfile.lock docker/invoke.sh /app-setup/
RUN chmod +x invoke.sh

ADD https://raw.githubusercontent.com/eficode/wait-for/master/wait-for /app-setup/wait-for
RUN chmod +x wait-for

RUN bundle install

WORKDIR /app
CMD ["/app-setup/invoke.sh"]
