version: '3'

services:
  app:
    build:
      context: ./
    environment:
      - RAILS_LOG_TO_STDOUT=true
    image: 'suldlss/rialto-webapp:latest'
    ports:
      - "3000"
  ruby:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.ruby
    image: 'suldlss/rialto-webapp:ruby-latest'
