version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: suldlss/rialto-webapp
    docker:
    - image: circleci/ruby:2.6.2-stretch-node
      environment:
        RAILS_ENV=production
jobs:
  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.2-stretch-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: rialto_test
          POSTGRES_PASSWORD: ""
      - image: solr:7
        command: bin/solr -cloud -noprompt -f -p 8983
    steps:
    - checkout

    - run:
        name: Install/Upgrade Bundler
        command: gem install bundler
    - run:
        name: Which version of bundler?
        command: bundle -v
    - restore_cache:
        keys:
        - app-bundle-v2-{{ checksum "Gemfile.lock" }}
        - app-bundle-v2-
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - save_cache:
        key: app-bundle-v2-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    - restore_cache:
        keys:
          - app-yarn-{{ checksum "yarn.lock" }}
          - app-yarn-
    - run:
        name: Yarn Install
        command: yarn install --cache-folder ~/.cache/yarn
    - save_cache:
        key: app-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

    - run:
        name: Check styles using rubocop
        command: bundle exec rubocop

    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
    - run:
        name: Database setup
        command: bin/rails db:schema:load --trace

    # Create a Solr collection
    - run:
        name: Load config into SolrCloud
        command: |
          cd solr/conf
          zip -1 -r solr_config.zip ./*
          curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=blacklight-core"
          curl -H 'Content-type: application/json' http://localhost:8983/api/collections/ -d '{create: {name: blacklight-core, config: blacklight-core, numShards: 1}}'

    - run:
        name: Setup Code Climate test-reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
    - run:
        name: Run rspec tests
        command: bundle exec rspec
    - run:
        name: Run javascript unit tests
        command: npm test
    - run:
        name: upload test coverage report to Code Climate
        command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
    # Save test results for timing analysis
    - store_test_results:
        path: test_results

  build-image:
    executor: docker-publisher
    steps:
    - checkout
    - setup_remote_docker
    # Upgrade bundler
    - run:
        name: Install Bundler
        command: gem install bundler

    # Which version of bundler?
    - run:
        name: Which bundler?
        command: bundle -v

    - run:
        name: Bundle Install
        command: bundle check || bundle install

    - run:
        name: Build Docker image
        command: |
          echo $MASTER_KEY > config/master.key
          ./bin/build

    - run:
        name: Archive Docker image
        command: |
          docker save -o image.tar $IMAGE_NAME

    - persist_to_workspace:
        root: .
        paths:
        - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - setup_remote_docker
    - run:
        name: Load archived Docker image
        command: |
          docker load -i /tmp/workspace/image.tar

    - run:
        name: Publish Docker Image to Docker Hub
        command: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push $IMAGE_NAME:latest

  publish-tag:
    executor: docker-publisher
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - setup_remote_docker
    - run:
        name: Load archived Docker image
        command: |
          docker load -i /tmp/workspace/image.tar

    - run:
        name: Publish Docker Image to Docker Hub
        command: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_TAG
          docker push $IMAGE_NAME:$CIRCLE_TAG

workflows:
  version: 2

  test:
    jobs:
    - test

  build:
    jobs:
    - build-image:
        filters:
          branches:
            only: master
    - publish-latest:
        requires:
        - build-image
        filters:
          branches:
            only: master
  build-tags:
    jobs:
    - build-image:
        filters:
          tags:
            only: /^[0-9]+\.[0-9]+\.[0-9]+/
          branches:
            ignore: /.*/
    - publish-tag:
        requires:
        - build-image
        filters:
          tags:
            only: /^[0-9]+\.[0-9]+\.[0-9]+/
          branches:
            ignore: /.*/
