# define often used filter
filter_on_master_ignore_tags: &filter_on_master_ignore_tags
  filters:
    branches:
      only: master
    tags:
      ignore: /.*/

version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: dbuser
          POSTGRES_DB: rialto_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Check styles using rubocop
          command: bundle exec rubocop

      # Run rspec in parallel
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Run mocha
      - run:
          name: Run mocha
          command: npm test


      # Save test results for timing analysis
      - store_test_results:
          path: test_results

register_image:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
      - checkout
      - run:
          name: Build Image & Register Task
          command: |
            docker build -t suldlss/rialto-webapp:latest .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push suldlss/rialto-webapp:latest

workflows:
  version: 2

  deploy_master_to_demo:
    jobs:
      - build:
          <<: *filter_on_master_ignore_tags
      - register_image:
          requires:
            - build
          <<: *filter_on_master_ignore_tags

