<% local = File.exist?('/tmp/.s.PGSQL.5432') && File.stat('/tmp/.s.PGSQL.5432').socket? %>
default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 120000
  <% unless local %>
  username: <%= ENV.fetch('RDS_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('RDS_PASSWORD', '') %>
  host: <%= ENV.fetch('RDS_HOSTNAME', 'localhost') %>
  port: <%= ENV.fetch('RDS_PORT', '5432') %>
  <% end %>

development:
  <<: *default
  database: rialto_development

test:
  <<: *default
  database: rialto_test


production:
  <<: *default
  encoding: unicode
  pool: 50
  database: <%= ENV['RDS_DB_NAME'] %>
